server:
  error:
    include-message: always

spring:
  application:
    name: recrutai-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp:
        timeout: 30000
        writetimeout: 10000
        connectiontimeout: 30000
        auth: true
        starttls:
          enable: true
          require: true

springdoc:
  swagger-ui:
    groups-order: asc
    operations-sorter: method
    tags-sorter: alpha
