server:
  error:
    include-message: always

spring:
  application:
    name: recrutai-backend

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:recrutai_db
    username: recrutai-user
    password: pass123

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp:
        timeout: 30000
        writetimeout: 10000
        connectiontimeout: 30000
        auth: true
        starttls:
          enable: true
          require: true
